### ISSUE TITLE
请问下怎么运行在Mac上？

### ISSUE THREAD

**Issue by yancymin** [bitpeach/EarthLiveForMac#2]
如题，感谢～

**Comment by bitpeach** [comment]
- First, thank you for watching my codes. 

- Second, I feel so sorry about that my code has not been updated for a long time. My code is not so good as you imagined. My code is just for fun without considering user experience.
    - [x] If you hope to use the earth live wallpaper on your Android phone, you can download the APP called "[Mantou Earth](https://www.appinn.com/ooo-oxo-apps-earth/)".
    - [x] If you hope to use the earth live wallpaper on your Windows computer, you can download the software called "[EarthLive C# version](https://github.com/bitdust/EarthLiveSharp)".
    - [x] If you hope to use the earth live wallpaper on your MacOS computer, you can download the executable program called "[Mantou Earth for MacOS](https://bbs.feng.com/read-htm-tid-10226117-page-1.html)".
    - [ ] The codes above are recommended by me but not produced by me. Please be careful that the program about MacOS version may not be uninstalled easily. Because it is difficult to write codes running on the MacOS computer.

- Third, I am worried that my code may not be running normally on your MAC computer. However, several  months ago, my code can still work on my MAC of EI Captain OS. The running way is indicated as follows.

    :arrow_right_hook: Prepare a MAC computer with the LOW version MAC OS such as EI Captain. If your MAC OS is higher than EI Captain, I am sorry that you can test it by yourself.
    :arrow_right_hook: Download my codes. Normally, MAC computer has Python environment. You can open the Terminal in MAC computer. Then, you can type "Python" and "import PIL" one by one to check whether your MacOS computer has Pillow modules. If there is no any warning or messages, it means your computer has Pillow modules. If you get the warning like "ImportError: No module named PIL", you should open a new terminal to use the command "pip install Pillow".
    :arrow_right_hook: Go to a CDN platform named [Cloudinary](http://cloudinary.com/) and sign up an account. The details of sign-up process can be referred as [this web page](https://github.com/bitdust/EarthLiveSharp/issues/13).
    :arrow_right_hook: Please remember to replace the line 18 in my code by your Cloudinary account name.
    :arrow_right_hook: Please remember to revise the line 100 in my code by the proper time. The code `"time.sleep(600)"` means the wallpaper will change in the next 10 minutes. Too short time to change the wallpaper will bring too much caching file garbage. So you can set this value a bit higher such as "time.sleep(3600)".
    :arrow_right_hook: Running any version of earth live wallpaper including my codes need your computer connecting the Internet.
    :arrow_right_hook: If the above steps are prepared, please open the terminal and input the command like "python wallpaper_earthlive_for_mac.py". Please do not shut down the terminal.

    >中文教程
    >1.准备苹果电脑，操作系统版本为Yosemite或EI Captain最佳。本人自用代码运行环境是EI Captain
    >2.全程联网
    >3.测试苹果电脑的Python环境，是否具有Pillow模块。如果有该模块，继续下一步。
    >4.前往CDN加速的图片爬取平台注册账户，注册后会有一个账户ID，将账户ID名字替换源代码的第18行。
    >5.修改源代码的第100行，该行表示每600秒就会请求一次联网更新，可能产生太多缓存文件垃圾，建议改为3600秒，即每1小时更新一次地球壁纸。
    >6.打开终端界面，输入指令“python wallpaper_earthlive_for_mac.py”，保持终端不关闭。然后，在苹果电脑设置里，进入壁纸设置，设置文件夹内图片自动播放，并将苹果电脑的壁纸文件夹路径切换为“\$HOME$\Pictures”。最后，将鼠标光标放在桌面空白处，点击切换下一页桌面即可，后续应该自动更新播放（如果没有的话，我只好跪了）。在代码介绍页面，明确了源代码的局限性(The Limitation of EarthLiveForMac)，无法自启动，需要开着终端运行界面，也明确了本人代码确实写得好烂。
    >6.看完上述教程，一定会厌恶，并且放弃的。没关系的，因为我已经放弃了。:grin:上述教程体验不佳，请忽略。:stuck_out_tongue:
    >7.最佩服网页设计、前端界面设计的前辈了，您设计的一些图片真的很好看，赞:octocat:。
    >8.如果确实想要体验一番，可以使用[上述其中一个帖子](https://bbs.feng.com/read-htm-tid-10226117-page-1.html)的macos程序，不必使用我的代码。不过，推荐帖子的代码，请注意安装或运行此类代码有一定的不良体验，比如代码不开源、不方便卸载、系统设置有改动等等。Anyway，不管怎样， 这个帖子的代码比我写的好，还是值得体验的。

- Then, after you scan this tutorial, I think that you may feel this code boring :smile: and will give up it :trollface:.

![](https://user-images.githubusercontent.com/6924631/36720532-51f8adba-1be3-11e8-9692-a642991cb0a9.jpg)


- Finally, thank you again.

**Comment by yancymin** [comment]
感谢那么详细的回复，我去试试啦。
